"""Latest local preview videos. Reset only this managed debug session."""
import json
import threading
import uuid
from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse

from backend.local_assessment_preview import is_local_assessment_preview

router = APIRouter(prefix="/debug")
DEBUG_DIR = Path(__file__).resolve().parent / ".local_state" / "assessment-debug" / "latest"
TASK_IDS = {"T1", "T2", "T3", "T4", "H1", "H2", "H3", "H4", "L1", "L2", "L3", "L4", "L5", "L6"}
VIDEO_TYPES = {"video/webm": "webm", "video/mp4": "mp4", "video/quicktime": "mov", "video/x-m4v": "m4v"}
MAX_VIDEO_BYTES = 1024 * 1024 * 1024
MAX_EVIDENCE_BYTES = 4 * 1024 * 1024
_lock = threading.RLock()


def guard(request):
    if not is_local_assessment_preview(request):
        raise HTTPException(404, "Local assessment debugging is unavailable")


def require_session(session_id):
    path = DEBUG_DIR / "session.json"
    if not path.is_file() or json.loads(path.read_text(encoding="utf-8"))["session_id"] != session_id:
        raise HTTPException(409, "A newer assessment has replaced this debug session")


def write_json(path, value):
    temporary = path.with_suffix(".json.tmp")
    temporary.write_text(json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False), encoding="utf-8")
    temporary.replace(path)


@router.post("/sessions")
async def start_session(request: Request):
    guard(request)
    with _lock:
        DEBUG_DIR.mkdir(parents=True, exist_ok=True)
        # Do not recursively delete directories or touch historical/account files.
        # Only fixed filenames generated by this service belong to the latest set.
        for path in DEBUG_DIR.iterdir():
            if path.is_file() and (path.name in {"session.json", "session.json.tmp"}
                or any(path.name == f"{task}.{suffix}" for task in TASK_IDS
                    for suffix in [*VIDEO_TYPES.values(), "json", "json.tmp"])):
                path.unlink()
        session = {"session_id": uuid.uuid4().hex, "started_at": datetime.now(timezone.utc).isoformat(),
                   "path": str(DEBUG_DIR.resolve()), "tasks": {}, "microphone_recorded": False}
        write_json(DEBUG_DIR / "session.json", session)
    return session


@router.post("/sessions/{session_id}/tasks/{task_id}/video")
async def save_video(session_id: str, task_id: str, request: Request, duration_ms: int = 0):
    guard(request)
    if task_id not in TASK_IDS:
        raise HTTPException(422, "Unknown assessment task")
    mime = request.headers.get("content-type", "").split(";", 1)[0].lower()
    if mime not in VIDEO_TYPES:
        raise HTTPException(415, "Use WebM, MP4, M4V or MOV video")
    with _lock:
        require_session(session_id)
    # Unique staging files cannot collide with a newer session or another upload.
    temporary = DEBUG_DIR.parent / f"{uuid.uuid4().hex}.part"
    size, header = 0, b""
    try:
        with temporary.open("xb") as output:
            async for chunk in request.stream():
                size += len(chunk)
                if size > MAX_VIDEO_BYTES:
                    raise HTTPException(413, "Debug video exceeds the 1 GB local limit")
                if len(header) < 32:
                    header = (header + chunk)[:32]
                output.write(chunk)
        valid = header.startswith(b"\x1a\x45\xdf\xa3") if mime == "video/webm" else header[4:8] == b"ftyp"
        if not valid:
            raise HTTPException(415, "Invalid video header")
        with _lock:
            # A previous page/upload must never repopulate a newly cleared set.
            require_session(session_id)
            filename = f"{task_id}.{VIDEO_TYPES[mime]}"
            path = DEBUG_DIR / filename
            for suffix in VIDEO_TYPES.values():
                if suffix != VIDEO_TYPES[mime]:
                    (DEBUG_DIR / f"{task_id}.{suffix}").unlink(missing_ok=True)
            temporary.replace(path)
            record = {"session_id": session_id, "task_id": task_id, "status": "video_saved",
                      "filename": filename, "path": str(path.resolve()), "content_type": mime,
                      "duration_ms": max(0, duration_ms), "size_bytes": size,
                      "evidence_path": str((DEBUG_DIR / f"{task_id}.json").resolve())}
            write_json(DEBUG_DIR / f"{task_id}.json", record)
            session = json.loads((DEBUG_DIR / "session.json").read_text(encoding="utf-8"))
            session["tasks"][task_id] = record
            write_json(DEBUG_DIR / "session.json", session)
        return record
    finally:
        temporary.unlink(missing_ok=True)


@router.post("/sessions/{session_id}/tasks/{task_id}/evidence")
async def save_evidence(session_id: str, task_id: str, request: Request):
    guard(request)
    if task_id not in TASK_IDS:
        raise HTTPException(422, "Unknown assessment task")
    body = bytearray()
    async for chunk in request.stream():
        body.extend(chunk)
        if len(body) > MAX_EVIDENCE_BYTES:
            raise HTTPException(413, "Debug evidence exceeds the local limit")
    try:
        evidence = json.loads(body)
        if not isinstance(evidence, dict) or evidence.get("task_result", {}).get("task_id") != task_id:
            raise ValueError("Task mismatch")
        json.dumps(evidence, allow_nan=False)
    except (ValueError, TypeError, AttributeError) as error:
        raise HTTPException(422, "Invalid debug evidence") from error
    with _lock:
        require_session(session_id)
        path = DEBUG_DIR / f"{task_id}.json"
        if not path.is_file():
            raise HTTPException(404, "Save the task video first")
        record = json.loads(path.read_text(encoding="utf-8"))
        record.update(status="saved", evidence=evidence)
        write_json(path, record)
    return {key: value for key, value in record.items() if key != "evidence"}


@router.get("/sessions/{session_id}/tasks/{task_id}/video")
async def play_video(session_id: str, task_id: str, request: Request):
    guard(request)
    if task_id not in TASK_IDS:
        raise HTTPException(404, "Unknown task")
    with _lock:
        require_session(session_id)
        metadata = DEBUG_DIR / f"{task_id}.json"
        if not metadata.is_file():
            raise HTTPException(404, "Video not recorded")
        record = json.loads(metadata.read_text(encoding="utf-8"))
    return FileResponse(DEBUG_DIR / record["filename"], media_type=record["content_type"], headers={"Cache-Control": "no-store"})
