// Records Alira's fixed lines once, in her one voice, into server/voice-pack.
// The pack is committed with the code, so those lines play without an API key and without
// spending ElevenLabs credits each time someone listens.
//
//   pnpm voice:bake              record every line that is missing, within the credits left
//   pnpm voice:bake --dry-run    report what is ready and what is missing; record nothing
//   pnpm voice:bake --max 2000   spend at most this many credits in this run
//   pnpm voice:bake --prune      also delete clips left over from an older voice or old lines
//   pnpm voice:bake --exercises  also record the exercise lines (off while exercises use the device voice)
//
// The key comes from ELEVENLABS_API_KEY in .env.local (never commit it). The voice comes from
// shared/alira-voice.ts, or ELEVENLABS_VOICE_ID when that is set.
import { existsSync } from "node:fs";
import {
  copyFile,
  mkdir,
  readdir,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { aliraVoicePhrases } from "../client/src/lib/alira-voice-phrases";
import {
  aliraVoiceKey,
  aliraVoicePackDir,
  readVoiceConfig,
} from "../server/alira-voice";
import { ALIRA_VOICE } from "../shared/alira-voice";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const prune = args.includes("--prune");
// Exercise lines are recorded only on request, while the exercises keep the device voice.
const withExercises = args.includes("--exercises");
const maxIndex = args.indexOf("--max");
const maxCredits = maxIndex >= 0 ? Number(args[maxIndex + 1]) : Infinity;
if (Number.isNaN(maxCredits) || maxCredits < 0)
  throw new Error("--max needs a number of credits, for example --max 2000");

const config = readVoiceConfig(root);
const packDir = aliraVoicePackDir(root);
const cacheDir = path.join(root, ".cache", "alira-elevenlabs");
const api = "https://api.elevenlabs.io";

// Input placeholders are registered with the other onboarding copy but are never read aloud.
const neverSpoken = (id: string) =>
  /^onboarding-placeholder-\d+$/.test(id) || (!withExercises && id.startsWith("exercise-"));
// When credits run short, the new patient's first conversation is recorded first.
// The emergency FAST check comes straight after; the daily exercises come last.
const rank = (id: string) =>
  id === "onboarding-adminDone"
    ? 9
    : /^(onboarding|guided)-/.test(id)
      ? 0
      : id.startsWith("topic-") || id.startsWith("fast-")
        ? 1
        : id.startsWith("exercise-")
          ? 3
          : 2;

type Line = { ids: string[]; text: string; key: string; file: string };
const byText = new Map<string, Line>();
for (const [id, text] of Object.entries(aliraVoicePhrases)
  .filter(([id]) => !neverSpoken(id))
  .map((entry, index) => ({ entry, index }))
  .sort((a, b) => rank(a.entry[0]) - rank(b.entry[0]) || a.index - b.index)
  .map(({ entry }) => entry)) {
  const line = byText.get(text);
  if (line) {
    line.ids.push(id);
    continue;
  }
  const key = aliraVoiceKey(config, text);
  byText.set(text, { ids: [id], text, key, file: `${key}.mp3` });
}
const lines = Array.from(byText.values());

async function elevenlabs(pathname: string, init?: RequestInit) {
  const response = await fetch(api + pathname, {
    ...init,
    headers: { "xi-api-key": config.apiKey, ...init?.headers },
    signal: AbortSignal.timeout(60000),
  });
  if (!response.ok) {
    const detail = await response.text().catch(() => "");
    throw new Error(
      `ElevenLabs answered ${response.status}: ${detail.slice(0, 300)}`
    );
  }
  return response;
}

async function writeManifest() {
  const clips: Record<string, unknown> = {};
  for (const line of lines) {
    const file = path.join(packDir, line.file);
    if (!existsSync(file)) continue;
    clips[line.file] = {
      phraseIds: line.ids,
      text: line.text,
      bytes: (await stat(file)).size,
    };
  }
  const manifest = {
    note: "Generated by `pnpm voice:bake`. The server finds clips by file name; this list is for people.",
    voice: {
      name:
        config.voiceId === ALIRA_VOICE.voiceId ? ALIRA_VOICE.name : "custom",
      voiceId: config.voiceId,
      modelId: config.modelId,
      outputFormat: ALIRA_VOICE.outputFormat,
      settings: ALIRA_VOICE.settings,
    },
    ready: Object.keys(clips).length,
    total: lines.length,
    clips,
  };
  await writeFile(
    path.join(packDir, "manifest.json"),
    JSON.stringify(manifest, null, 2) + "\n"
  );
}

async function main() {
  await mkdir(packDir, { recursive: true });
  // A line someone has already listened to is in the local cache: reuse it for free.
  for (const line of lines) {
    const packed = path.join(packDir, line.file);
    const cached = path.join(cacheDir, line.file);
    if (!existsSync(packed) && existsSync(cached) && !dryRun)
      await copyFile(cached, packed);
  }
  const missing = lines.filter(
    line => !existsSync(path.join(packDir, line.file))
  );
  const missingChars = missing.reduce((sum, line) => sum + line.text.length, 0);
  console.log(
    `Alira's voice: ${config.voiceId} (${config.modelId}). ` +
      `${lines.length - missing.length} of ${lines.length} lines are ready; ` +
      `${missing.length} missing (${missingChars} characters).`
  );

  if (prune && !dryRun) {
    // Exercise clips are kept even when this run doesn't record them.
    const keep = new Set([
      ...lines.map(line => line.file),
      ...Object.entries(aliraVoicePhrases)
        .filter(([id]) => id.startsWith("exercise-"))
        .map(([, text]) => `${aliraVoiceKey(config, text)}.mp3`),
      "manifest.json",
    ]);
    for (const name of await readdir(packDir)) {
      if (keep.has(name) || !name.endsWith(".mp3")) continue;
      await rm(path.join(packDir, name));
      console.log(`Removed ${name} (older voice or deleted line).`);
    }
  }
  if (dryRun || !missing.length) {
    if (!dryRun) await writeManifest();
    return;
  }
  if (!config.apiKey)
    throw new Error(
      "Add ELEVENLABS_API_KEY to .env.local before recording new lines."
    );
  if (
    !/^[a-zA-Z0-9_-]{1,100}$/.test(config.voiceId) ||
    !/^[a-zA-Z0-9_-]{1,100}$/.test(config.modelId)
  )
    throw new Error("The voice or model ID is not valid.");

  const subscription = (await (
    await elevenlabs("/v1/user/subscription")
  ).json()) as { character_count: number; character_limit: number };
  const models = (await (await elevenlabs("/v1/models")).json()) as {
    model_id: string;
    model_rates?: { character_cost_multiplier?: number };
  }[];
  const costPerCharacter =
    models.find(model => model.model_id === config.modelId)?.model_rates
      ?.character_cost_multiplier ?? 1;
  const available = subscription.character_limit - subscription.character_count;
  let budget = Math.min(available, maxCredits);
  console.log(
    `ElevenLabs has ${available} credits left this month; recording everything ` +
      `missing needs about ${Math.ceil(missingChars * costPerCharacter)}.`
  );

  let recorded = 0;
  let skipped = 0;
  for (const line of missing) {
    const cost = Math.ceil(line.text.length * costPerCharacter);
    if (cost > budget) {
      skipped += 1;
      continue;
    }
    const response = await elevenlabs(
      `/v1/text-to-speech/${config.voiceId}?output_format=${ALIRA_VOICE.outputFormat}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "audio/mpeg" },
        body: JSON.stringify({
          text: line.text,
          model_id: config.modelId,
          voice_settings: ALIRA_VOICE.settings,
        }),
      }
    );
    const bytes = Buffer.from(await response.arrayBuffer());
    if (
      !response.headers.get("content-type")?.startsWith("audio/") ||
      bytes.length < 1000
    )
      throw new Error(`ElevenLabs did not return audio for ${line.ids[0]}.`);
    await writeFile(path.join(packDir, line.file), bytes);
    budget -= cost;
    recorded += 1;
    console.log(`  recorded ${line.ids[0]} (${line.text.length} characters)`);
    await writeManifest();
  }
  await writeManifest();
  console.log(
    `Recorded ${recorded} lines.` +
      (skipped
        ? ` ${skipped} lines are still missing because the credits ran out; run this again after they renew.`
        : " Every line is ready.")
  );
}

main().catch(error => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
