// The story read in My Time. Each chapter is a list of short sentences: they are read aloud one at
// a time, and the one being read is highlighted. Edit the wording freely; keep sentences short.

export type StoryChapter = { title: string; sentences: string[] };

export const story: { title: string; chapters: StoryChapter[] } = {
  title: "The Lighthouse Garden",
  chapters: [
    {
      title: "The island",
      sentences: [
        "The lighthouse stood on a small island of grey rock.",
        "Maren had kept its lamp for eleven winters.",
        "Every evening she climbed the ninety steps and lit it.",
        "Every morning she climbed them again and put it out.",
        "Nothing grew on the island but moss and a little sea grass.",
        "The wind saw to that.",
        "Then one spring the supply boat brought a parcel she had not ordered.",
        "Inside was a paper packet of seeds, and a note from her sister.",
        "The note said, “For your garden.”",
        "Maren laughed out loud, alone on the rock.",
        "She did not have a garden.",
        "She put the packet on the kitchen shelf, beside the tea.",
        "It stayed there for a week, and she looked at it every day.",
      ],
    },
    {
      title: "The south wall",
      sentences: [
        "On the eighth day Maren walked round the lighthouse with her tea.",
        "On the south side, the tower made a shelter from the wind.",
        "The stones there were warm, even in April.",
        "She stood for a long time with her back against them.",
        "Then she fetched a bucket and went down to the shore.",
        "She carried up seaweed, and sand, and the dark soil from under the moss.",
        "It took her nine trips, and she rested after every one.",
        "By evening there was a bed of earth as long as a rowing boat.",
        "It did not look like much.",
        "She pressed the seeds in with one finger, a hand’s width apart.",
        "She watered them from the kettle.",
        "Then she climbed the ninety steps and lit the lamp, the same as always.",
      ],
    },
    {
      title: "Waiting",
      sentences: [
        "For two weeks nothing happened.",
        "Maren looked at the bare earth each morning, and the earth looked back.",
        "She began to feel a little foolish.",
        "The boy from the supply boat asked what she was staring at.",
        "“A garden,” she said.",
        "He looked at the mud, and then at her, and politely said nothing.",
        "On the fifteenth morning there was a green thread in the soil.",
        "It was thinner than a pin.",
        "By the end of the week there were thirty of them.",
        "Maren counted them twice.",
        "She did not know yet what they were, only that they had decided to come.",
        "She found she was humming on the stairs that night.",
      ],
    },
    {
      title: "The storm passes",
      sentences: [
        "The storm came in June, out of a clear sky.",
        "Maren saw it from the lamp room, a dark wall walking over the water.",
        "She ran down all ninety steps.",
        "She lifted the seedlings into trays and carried them inside, one tray at a time.",
        "The wind took her hat and did not give it back.",
        "All night the sea threw itself at the rock.",
        "Maren kept the lamp burning and the kettle warm.",
        "The trays sat in a row on the kitchen floor.",
        "By morning the wind had worn itself out.",
        "Maren carried the seedlings back to the south wall, one tray at a time.",
        "Some were bent, and she propped them up with twigs.",
        "None were lost.",
      ],
    },
    {
      title: "What they were",
      sentences: [
        "In July the plants told her what they were.",
        "First came sweet peas, climbing the string she had tied for them.",
        "Then marigolds, as orange as the lamp.",
        "Then a row of something feathery that turned out to be carrots.",
        "The boy from the supply boat stood and stared.",
        "“It is a garden,” he said.",
        "“I did tell you,” said Maren.",
        "She cut him a bunch of sweet peas to take home to his mother.",
        "He held them the whole way back, out of the spray.",
        "After that, the boat seemed to arrive a little early each week.",
        "Sailors who had never once waved began to wave.",
        "From the water, they said, you could see a line of colour at the foot of the tower.",
      ],
    },
    {
      title: "Seeds",
      sentences: [
        "In autumn the flowers faded, as flowers do.",
        "Maren did not mind as much as she had expected.",
        "She sat by the south wall with a bowl in her lap.",
        "One by one she shook the dry seed heads over it.",
        "There were far more seeds than had come in the packet.",
        "She saved half for her own spring.",
        "The other half she folded into small paper envelopes.",
        "On each one she wrote, “For your garden.”",
        "She gave them to the boy, to hand out along the coast.",
        "That winter the wind blew as hard as ever.",
        "Maren climbed the ninety steps each evening and lit the lamp.",
        "And on the kitchen shelf, beside the tea, the seeds waited with her.",
      ],
    },
  ],
};
